### ISSUE TITLE
Error message when I go to settings

### ISSUE THREAD

**Issue by digicali** [MaxLazar/mx-mailgun#1]
EE 6.0.1  Fresh install

Notice
Undefined index: enable
user/addons/mx_mailgun/ext.mx_mailgun.php, line 143

Severity: E_NOTICE
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/ExpressionEngine/Boot/boot.common.php, line 475

**Comment by MaxLazar** [comment]
Thanks for the report! 
Fixed
